# Generated by Django 4.0.6 on 2022-09-16 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('banner_url', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('years_playing', models.PositiveSmallIntegerField(default=1)),
                ('discord', models.CharField(max_length=50)),
                ('week_days', models.CharField(max_length=13)),
                ('hour_start', models.PositiveIntegerField(default=720, help_text='In minutes')),
                ('hour_end', models.PositiveIntegerField(default=780, help_text='In minutes')),
                ('use_voice_channel', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='esports.game')),
            ],
        ),
    ]
